### ISSUE TITLE
site-shield list-maps throws a Python error related to str/int type

### ISSUE THREAD

**Issue by ghost** [akamai/cli-firewall#22]
akamai ss --version
site-shield, version 0.2.1

akamai ss list-maps
Fetching Site Shield Maps...
Traceback (most recent call last):
  File "/cli/.akamai-cli/src/cli-firewall/bin/akamai-site-shield", line 331, in <module>
    status = cli(prog_name='site-shield')
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/cli/.akamai-cli/src/cli-firewall/bin/akamai-site-shield", line 124, in list_maps
    datetime.datetime.fromtimestamp(acknowledgedOn / 1000))
TypeError: unsupported operand type(s) for /: 'str' and 'int'

**Comment by vreddhi** [comment]
There appears to be a string to timestamp conversion issue. https://github.com/akamai/cli-firewall/pull/23
