### ISSUE TITLE
Error when returning a SiteShield map that has been Acknowledge

### ISSUE THREAD

**Issue by justinrummel** [akamai/cli-firewall#9]
If a map has been Acknowledge by a customer, the package throws an error.

``` python
jrummel@res-mp4pu ~> akamai ss list-maps --section=my_test_api
/Users/jrummel/.akamai-cli/src/cli-firewall/lib/python/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Fetching Site Shield Maps...
Traceback (most recent call last):
  File "/Users/jrummel/.akamai-cli/src/cli-firewall/bin/akamai-site-shield", line 436, in <module>
    status = cli()
  File "/Users/jrummel/.akamai-cli/src/cli-firewall/bin/akamai-site-shield", line 162, in cli
    return getattr(sys.modules[__name__], args.command.replace("-", "_"))(args)
  File "/Users/jrummel/.akamai-cli/src/cli-firewall/bin/akamai-site-shield", line 256, in list_maps
    acknowledgedBy = eachItem['acknowledgedBy']
KeyError: 'acknowledgedBy'
```

This key is only populated if an ACK is pending, else it is not returned.  You can see when using HTTPie the delta between the following two maps:

``` python
jrummel@res-mp4pu ~> http -A edgegrid -a my_test_api: ":/siteshield/v1/maps" | jq '.siteShieldMaps[] | keys'
[
  "acknowledgeRequiredBy",
  "acknowledged",
  "acknowledgedBy", <-- unique key
  "acknowledgedOn",
  "contacts",
  "currentCidrs",
  "id",
  "latestTicketId",
  "mapAlias",
  "mcmMapRuleId",
  "proposedCidrs",
  "ruleName",
  "service",
  "shared",
  "sureRouteName",
  "type"
]
[
  "acknowledgeRequiredBy",
  "acknowledged",
  "contacts",
  "currentCidrs",
  "id",
  "latestTicketId",
  "mapAlias",
  "mcmMapRuleId",
  "proposedCidrs",
  "ruleName",
  "service",
  "shared",
  "sureRouteName",
  "type"
]
```

**Comment by aetsai** [comment]
closed in v0.2.0
